import Link from "next/link";

const IMPROVEMENTS = [
  {
    id: 1,
    title: "Multi-Generator Paraphrases",
    status: "done" as const,
    severity: "High",
    problem:
      "ChatGPT generates all query paraphrases, which biases the benchmark toward OpenAI phrasing preferences. When ChatGPT creates the variations, it phrases them in ways ChatGPT is good at answering — giving itself an unfair advantage over Claude and Gemini.",
    fix:
      "Use all 3 models (ChatGPT, Claude, Gemini) to generate paraphrases independently, pool the results, and semantically deduplicate using SequenceMatcher (similarity threshold 0.85). The result is a diverse query set not biased toward any single model's phrasing.",
    flag: "multi_generator_fanout=True",
    before: {
      label: "Single-model paraphrases (all ChatGPT-phrased)",
      queries: [
        "best AI services for lab platforms",
        "top AI solutions for laboratory platforms",
        "leading AI services for lab environments",
      ],
      note: "3 queries — all generated by ChatGPT, biased toward OpenAI phrasing patterns",
    },
    after: {
      label: "Multi-generator paraphrases (3 models)",
      queries: [
        "best AI services for lab platforms",
        "top AI solutions for laboratory platforms",
        "leading AI services for lab environments",
        "premier artificial intelligence tools for laboratory settings",
        "recommended AI platforms for scientific labs",
        "which AI services are most suitable for lab work",
        "AI-powered laboratory platform solutions",
      ],
      note: "7 queries — ChatGPT, Claude, and Gemini each contributed, deduplicated at 0.85 similarity",
    },
  },
  {
    id: 2,
    title: "Intent Fan-Out",
    status: "done" as const,
    severity: "Medium",
    problem:
      '"best/top/leading" are synonym variations that test the same buying intent. What actually matters is intent diversity: comparison queries, use-case queries, objection queries, persona queries, and budget queries. Research shows 1/3 of AI citations come from fan-out queries with zero traditional search volume.',
    fix:
      "For each base query, generate 5 intent-diverse variants using an intent tree: comparison (alternatives to X), use-case (for biotech / for enterprise), objection (compliance, security), persona (CTO vs researcher), budget (cheapest / best value). Intent expansion runs on base queries only to avoid combinatorial explosion.",
    flag: "intent_fanout=True",
    before: {
      label: "Synonym paraphrases only",
      queries: [
        "best AI services for lab platforms",
        "top AI solutions for laboratory platforms",
        "leading AI services for lab environments",
      ],
      note: '3 queries — all ask the same thing with different words ("best/top/leading")',
    },
    after: {
      label: "Intent-diverse query tree",
      queries: [
        "best AI services for lab platforms",
        "alternatives to LabArchives for lab data management",
        "AI tools for biotech startups with small teams",
        "which AI lab platforms are HIPAA compliant",
        "best AI lab platform for a research director",
        "cheapest AI tools for academic research labs",
        "top AI solutions for laboratory platforms",
        "leading AI services for lab environments",
      ],
      note: "8 queries — covers comparison, use-case, objection, persona, and budget intents",
    },
  },
  {
    id: 3,
    title: "Independent Extraction (Cross-Validation)",
    status: "done" as const,
    severity: "High",
    problem:
      "We ask the LLM to list brands it mentioned, then trust that list. The model is grading itself. If ChatGPT says it mentioned \"aivalanche\" at position #1, we recorded that as a real mention — but ChatGPT was just being compliant with our old prompt that said \"check these brands.\" Even with the organic prompt, the self-reported JSON can include brands the model name-dropped without genuinely recommending.",
    fix:
      "After getting the primary response, send the raw text to a DIFFERENT model for independent brand extraction. Rotation: ChatGPT responses verified by Claude, Claude by Gemini, Gemini by ChatGPT. If both extractors agree a brand is mentioned, it counts. If they disagree, it's flagged as an extraction conflict. Conservative merge: only count brands both agree on. Configurable rate (default 50% of calls verified to manage API cost).",
    flag: "cross_validate_extraction=True",
    before: {
      label: "Self-reported extraction (model grades itself)",
      queries: [
        'ChatGPT response mentions "aivalanche" in JSON → recorded as mentioned ✓',
        "No second opinion — if the model hallucinated, we wouldn't know",
        "Result: aivalanche gets 33% mention rate (false positive)",
      ],
      note: "Trust the answering model's own JSON output — prone to false positives",
    },
    after: {
      label: "Cross-validated extraction (independent verifier)",
      queries: [
        "ChatGPT response → sent to Claude for independent brand extraction",
        'Claude reads the response: "aivalanche is not meaningfully discussed" → disagreement flagged',
        "Result: aivalanche gets 0% mention rate (honest)",
        "Extraction conflicts logged for admin review",
      ],
      note: "Two models must agree. Disagreements flagged. Conservative merge prevents false positives.",
    },
  },
];

const statusStyles = {
  done: "bg-emerald-50 text-emerald-800 border-emerald-200",
  "in-progress": "bg-amber-50 text-amber-800 border-amber-200",
  planned: "bg-gray-50 text-gray-600 border-gray-200",
};

const severityStyles: Record<string, string> = {
  High: "bg-rose-50 text-rose-700 border-rose-200",
  Medium: "bg-amber-50 text-amber-700 border-amber-200",
  Low: "bg-gray-50 text-gray-600 border-gray-200",
};

export default function ImprovementsPage() {
  return (
    <div className="mx-auto max-w-5xl px-6 py-10">
      {/* Header */}
      <Link href="/simulator" className="ink-link text-sm">
        Back to engine
      </Link>
      <h1 className="mt-2 text-4xl text-[var(--ink)] md:text-5xl">
        Engine Improvements
      </h1>
      <p className="mt-2 max-w-2xl text-sm leading-relaxed text-[var(--muted)]">
        Every methodological change to the collection engine, with before/after
        examples showing exactly what improved and why.
      </p>

      {/* Status summary */}
      <div className="mt-8 grid gap-4 sm:grid-cols-3">
        {IMPROVEMENTS.map((imp) => (
          <div key={imp.id} className="metric-card">
            <div className="flex items-center justify-between mb-2">
              <span className="text-xs font-semibold text-[var(--muted)]">
                #{imp.id}
              </span>
              <span
                className={`rounded-full border px-2.5 py-0.5 text-[10px] font-semibold ${statusStyles[imp.status]}`}
              >
                {imp.status}
              </span>
            </div>
            <p className="text-sm font-semibold text-[var(--ink)]">
              {imp.title}
            </p>
            <p className="mt-1 text-xs text-[var(--muted)]">
              Severity: {imp.severity}
            </p>
          </div>
        ))}
      </div>

      {/* Improvement cards */}
      <div className="mt-10 space-y-8">
        {IMPROVEMENTS.map((imp) => (
          <div key={imp.id} className="paper-panel rounded-[2rem] p-6">
            {/* Title bar */}
            <div className="flex flex-wrap items-center gap-3 mb-4">
              <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-[var(--ink)] text-sm font-bold text-[var(--paper)]">
                {imp.id}
              </span>
              <h2 className="text-2xl text-[var(--ink)] flex-1">
                {imp.title}
              </h2>
              <span
                className={`rounded-full border px-3 py-1 text-xs font-semibold ${severityStyles[imp.severity]}`}
              >
                {imp.severity}
              </span>
              <span
                className={`rounded-full border px-3 py-1 text-xs font-semibold ${statusStyles[imp.status]}`}
              >
                {imp.status}
              </span>
            </div>

            {/* Problem */}
            <div className="mb-4">
              <p className="text-xs font-semibold uppercase tracking-wider text-rose-700 mb-1">
                Problem
              </p>
              <p className="text-sm leading-relaxed text-[var(--muted)]">
                {imp.problem}
              </p>
            </div>

            {/* Fix */}
            <div className="mb-4">
              <p className="text-xs font-semibold uppercase tracking-wider text-emerald-700 mb-1">
                Fix
              </p>
              <p className="text-sm leading-relaxed text-[var(--muted)]">
                {imp.fix}
              </p>
            </div>

            {/* API flag */}
            <div className="mb-6">
              <p className="text-xs font-semibold uppercase tracking-wider text-[var(--muted)] mb-1">
                Enable via API
              </p>
              <code className="text-xs font-mono bg-[rgba(255,255,255,0.5)] rounded px-2 py-1 text-[var(--ink)]">
                {imp.flag}
              </code>
            </div>

            {/* Before / After */}
            <div className="grid gap-4 md:grid-cols-2">
              {/* Before */}
              <div className="paper-card rounded-[1.4rem] p-5">
                <div className="flex items-center gap-2 mb-3">
                  <span className="flex h-6 w-6 items-center justify-center rounded-full bg-[rgba(114,105,92,0.15)] text-[10px] font-bold text-[var(--muted)]">
                    A
                  </span>
                  <span className="text-xs font-semibold uppercase tracking-wider text-[var(--muted)]">
                    Before
                  </span>
                </div>
                <p className="text-xs font-medium text-[var(--ink)] mb-3">
                  {imp.before.label}
                </p>
                <div className="space-y-1.5">
                  {imp.before.queries.map((q, i) => (
                    <div
                      key={i}
                      className="surface-inset rounded-xl px-3 py-2 text-xs text-[var(--ink)] font-mono leading-relaxed"
                    >
                      {q}
                    </div>
                  ))}
                </div>
                <p className="mt-3 text-[10px] text-[var(--muted)]">
                  {imp.before.note}
                </p>
              </div>

              {/* After */}
              <div className="paper-card rounded-[1.4rem] p-5 border-2 border-[var(--ink)]">
                <div className="flex items-center gap-2 mb-3">
                  <span className="flex h-6 w-6 items-center justify-center rounded-full bg-[var(--ink)] text-[10px] font-bold text-[var(--paper)]">
                    B
                  </span>
                  <span className="text-xs font-semibold uppercase tracking-wider text-[var(--ink)]">
                    After
                  </span>
                </div>
                <p className="text-xs font-medium text-[var(--ink)] mb-3">
                  {imp.after.label}
                </p>
                <div className="space-y-1.5">
                  {imp.after.queries.map((q, i) => (
                    <div
                      key={i}
                      className="surface-inset rounded-xl px-3 py-2 text-xs text-[var(--ink)] font-mono leading-relaxed"
                    >
                      {q}
                    </div>
                  ))}
                </div>
                <p className="mt-3 text-[10px] text-[var(--muted)]">
                  {imp.after.note}
                </p>
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* Planned improvements */}
      <div className="mt-10 paper-panel rounded-[2rem] p-6">
        <h2 className="text-2xl text-[var(--ink)] mb-4">Coming next</h2>
        <div className="space-y-3">
          {[
            {
              title: "Per-model ranking models",
              desc: "Train separate surrogates for ChatGPT, Claude, and Gemini instead of one aggregate model. Each model has different citation behavior (Yext 17.2M study).",
            },
            {
              title: "Content analysis from website URL",
              desc: "Crawl the user's website to extract GEO features (statistics density, quotation count, freshness, content length) as independent variables for the surrogate model.",
            },
            {
              title: "Temporal validation (lagged features)",
              desc: "Predict next-week's mention rate from this-week's content features, not same-day regression. Requires 30+ days of accumulated data.",
            },
            {
              title: "Weekly backtesting",
              desc: "Compare last week's predictions to this week's actual mention rates. Automated model quality tracking.",
            },
          ].map((item) => (
            <div
              key={item.title}
              className="paper-card rounded-[1.4rem] p-4 flex items-start gap-3"
            >
              <span className="rounded-full border border-gray-200 bg-gray-50 px-2.5 py-0.5 text-[10px] font-semibold text-gray-500 shrink-0 mt-0.5">
                planned
              </span>
              <div>
                <p className="text-sm font-semibold text-[var(--ink)]">
                  {item.title}
                </p>
                <p className="mt-1 text-xs text-[var(--muted)]">{item.desc}</p>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Footer */}
      <div className="mt-12 border-t border-[color:var(--line)] pt-8 flex justify-center gap-6">
        <Link href="/simulator" className="ink-link text-sm">
          Engine
        </Link>
        <Link href="/admin/logs" className="ink-link text-sm">
          API Logs
        </Link>
        <Link href="/concept" className="ink-link text-sm">
          How it works
        </Link>
      </div>
    </div>
  );
}
